# sudo service docker start
version: "3.1"

services:
  db:
    image: postgres
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.local

  session:
    image: redis

  api:
    image: mpetrus/post-feed-express:1.0.1
    depends_on:
      - db
      - session
    ports:
      - "127.0.0.1:4000:4000"
    env_file:
      - .env.local
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: session
