# sudo service docker start
version: "3.1"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db

  adminer:
    depends_on:
      - postgres
    image: adminer
    ports:
      - 8080:8080

  redis:
    image: redis
    ports:
      - 6379:6379
