# sudo service docker start
version: "3.1"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file: .env.dev

  adminer:
    depends_on:
      - postgres
    image: adminer
    ports:
      - 8080:8080

  redis:
    image: redis
    ports:
      - 6379:6379
