# sudo service docker start
version: "3.1"

services:
  db:
    image: postgres
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  session:
    image: redis

  app:
    image: mpetrus/post-feed-express:1.0.0
    depends_on:
      - db
      - session
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_HOST: session
      REDIS_SECRET: ${REDIS_SECRET}
